# Matrices & Tensors

## Basic Matrix Operations

In [ ]:
import numpy as np

# Create matrices
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

# Matrix multiplication
C = np.dot(A, B)  # or A @ B in modern Python
print("Matrix multiplication result:")
print(C)

# Common operations in ML
# Transpose
print("\nTranspose of A:")
print(A.T)

# Matrix inverse
square_matrix = np.array([[1, 2], [3, 4]])
inverse = np.linalg.inv(square_matrix)
print("\nInverse of 2x2 matrix:")
print(inverse)

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(square_matrix)
print("\nEigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Matrix multiplication result:
[[ 58  64]
 [139 154]]

Transpose of A:
[[1 4]
 [2 5]
 [3 6]]

Inverse of 2x2 matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


## Features used in ML
Pairwise distance calcuation (oftend used in clustering) & Feature *scaling*

In [ ]:
# Example: Computing distances between points (used in k-means, KNN)
points = np.array([[1, 2], [3, 4], [5, 6]])
distances = np.sqrt(np.sum((points[:, np.newaxis] - points) ** 2, axis=2))
print("\nPairwise distances between points:")
print(distances)

# Example: Feature scaling (common preprocessing step)
features = np.array([[1, 1000],
                    [2, 2000],
                    [3, 3000]])
mean = features.mean(axis=0)
std = features.std(axis=0)
scaled_features = (features - mean) / std
print("\nScaled features:")
print(scaled_features)



Pairwise distances between points:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]

Scaled features:
[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


# Tensors

## Tensor Dimensions

In [ ]:
# 0D Tensor (Scalar)
scalar = np.array(25)
print("0D Tensor (Scalar):", scalar)

# 1D Tensor (Vector)
vector = np.array([1, 2, 3, 4])
print("\n1D Tensor (Vector):", vector)

# 2D Tensor (Matrix)
matrix = np.array([[1, 2, 3],
                  [4, 5, 6]])
print("\n2D Tensor (Matrix):\n", matrix)

# 3D Tensor (Cube)
cube = np.array([[[1, 2], [3, 4]],
                 [[5, 6], [7, 8]]])
print("\n3D Tensor (Cube):\n", cube)


0D Tensor (Scalar): 25

1D Tensor (Vector): [1 2 3 4]

2D Tensor (Matrix):
 [[1 2 3]
 [4 5 6]]

3D Tensor (Cube):
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Tensor Operations

In [ ]:
# Generate a batch of images example (4D tensor: batch_size x height x width x channels)
batch_size, height, width, channels = 32, 28, 28, 3
images = np.random.rand(batch_size, height, width, channels)

# Reshaping tensors (common in ML pipelines)
flattened = images.reshape(batch_size, -1)
print(f"\nReshaped from {images.shape} to {flattened.shape}")

# Tensor slicing (extracting features)
first_image = images[0]       # Get first image
red_channel = images[..., 0]  # Get red channel for all images



Reshaped from (32, 28, 28, 3) to (32, 2352)
